import { useMemo, useState, useEffect } from 'react';
import ReactFlow, { Background, Controls, MiniMap, type Edge, type Node } from 'reactflow';
import 'reactflow/dist/style.css';
import { toast } from 'sonner';
import { ErrorBoundary } from '../components/ErrorBoundary';
import { Skeleton } from '../components/Skeleton';

const starterNodes: Node[] = [
  { id: 'trigger', data: { label: 'Trigger: New lead submitted' }, position: { x: 80, y: 60 } },
  { id: 'action1', data: { label: 'Action: Send welcome email' }, position: { x: 320, y: 60 } },
  { id: 'action2', data: { label: 'Action: Add contact to CRM' }, position: { x: 560, y: 60 } }
];

const starterEdges: Edge[] = [
  { id: 'e1', source: 'trigger', target: 'action1' },
  { id: 'e2', source: 'action1', target: 'action2' }
];

export function WorkflowBuilderPage() {
  const [nodes, setNodes] = useState(starterNodes);
  const [edges] = useState(starterEdges);
  const [loading, setLoading] = useState(false);
  const [prompt, setPrompt] = useState('');
  const [logs, setLogs] = useState<string[]>([]);

  useEffect(() => {
    const ws = new WebSocket('ws://localhost:4000/api/v1/execution-stream');
    ws.onmessage = (event) => setLogs((prev) => [event.data, ...prev].slice(0, 20));
    ws.onerror = () => toast.error('Execution log stream disconnected');
    return () => ws.close();
  }, []);

  const onGenerate = async () => {
    if (!prompt) return;
    setLoading(true);
    try {
      const response = await fetch('http://localhost:4000/api/v1/copilot/generate-workflow', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          prompt,
          triggerCatalog: [{ type: 'webhook.lead.created', description: 'New lead webhook' }],
          actionCatalog: [
            { type: 'gmail.send', description: 'Send email via Gmail' },
            { type: 'hubspot.contact.create', description: 'Create CRM contact' }
          ]
        })
      });
      const data = await response.json();
      const generatedNodes = [
        { id: 'g-trigger', data: { label: `Trigger: ${data.workflow.trigger.type ?? 'generated'}` }, position: { x: 40, y: 120 } },
        ...data.workflow.actions.map((action: { type: string }, index: number) => ({
          id: `g-action-${index}`,
          data: { label: `Action: ${action.type}` },
          position: { x: 300 + index * 220, y: 120 }
        }))
      ];
      setNodes(generatedNodes);
      toast.success('Workflow generated by AI copilot');
    } catch {
      toast.error('Failed to generate workflow');
    } finally {
      setLoading(false);
    }
  };

  const canvas = useMemo(
    () => (
      <div className="h-[520px] w-full rounded-xl border border-zinc-300 bg-white dark:border-zinc-700 dark:bg-zinc-900">
        <ReactFlow nodes={nodes} edges={edges} fitView>
          <MiniMap />
          <Controls />
          <Background />
        </ReactFlow>
      </div>
    ),
    [nodes, edges]
  );

  return (
    <ErrorBoundary>
      <main className="min-h-screen bg-zinc-50 p-4 text-zinc-900 md:p-8 dark:bg-zinc-950 dark:text-zinc-100">
        <section className="mx-auto flex w-full max-w-7xl flex-col gap-4">
          <h1 className="text-2xl font-semibold md:text-3xl">AutoFlowAI Workflow Builder</h1>
          <div className="grid gap-4 md:grid-cols-[2fr_1fr]">
            <div className="rounded-xl border border-zinc-300 p-3 dark:border-zinc-700">
              <label className="mb-2 block text-sm">Describe your automation</label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                className="h-24 w-full rounded-md border border-zinc-300 bg-white p-2 dark:border-zinc-700 dark:bg-zinc-900"
                placeholder="When a new lead submits the contact form, send welcome email and add to CRM"
              />
              <button
                onClick={onGenerate}
                className="mt-3 rounded-md bg-blue-600 px-4 py-2 text-white hover:bg-blue-500"
              >
                Generate with AI Copilot
              </button>
            </div>
            <div className="rounded-xl border border-zinc-300 p-3 dark:border-zinc-700">
              <h2 className="mb-2 text-sm font-semibold">Live execution logs</h2>
              <ul className="space-y-2 text-xs">
                {logs.map((log, idx) => (
                  <li key={`${log}-${idx}`} className="rounded bg-zinc-100 p-2 dark:bg-zinc-800">{log}</li>
                ))}
              </ul>
            </div>
          </div>
          {loading ? <Skeleton className="h-[520px] w-full" /> : canvas}
        </section>
      </main>
    </ErrorBoundary>
  );
}
